spring:
  jackson:
    default-property-inclusion: non_null
  main:
    banner-mode: "off"
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    banner: false

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
